### ISSUE TITLE
Question about the project

### ISSUE THREAD

**Issue by ayubix** [danielazevedo/Football-Analytics#2]
Hello , I noticed your soccer detetcion project and found it very helpful for me , since my final course project is about the same 
things(detetction objects/ computer vision / ml .... in the soccer world). We faced with so many issues with  the implemanting stage
so far  , and we trying to see how other projects approached to this problem . I tried to download your files  , but i do not know how to combine all of them to a one python file for running it and see the results and the work method . Maybe there is a master file that contain all the parts of the project in the proper order for executing on a pycharm environment ? 

thank you in advance and well done for the code

**Comment by danielazevedo** [comment]
Hi ayubix, sorry for the late reply. It is difficult to have a single main file as there are a lot of dependencies (datasets, credentials, etc) and time and computational limitations that makes it hard to run everything in a single run
