### ISSUE TITLE
Dataset used in Project

### ISSUE THREAD

**Issue by Abdullah-Fiaz** [danielazevedo/Football-Analytics#3]
Hello! I am interested in using the code from your project, but I need access to the dataset that was used in the project in order to run it. Could you please provide a link to the dataset or tell me where I can find it?

I appreciate your help, and thank you for sharing your project with the community.

**Comment by danielazevedo** [comment]
Hi @Abdullah-Fiaz! All the datasets I used are public and should be mentioned in the respective project (folder) documentation or commented in the code. Also, I used different datasets for the different projects present in this repository

**Comment by Abdullah-Fiaz** [comment]
I'm basicaly using the player detection files. So, I need that particular dataset but I couldn't find that dataset as it is used directly from the google drive. So, I want to your help and thank you in advance
